services:
  postgres:
    image: postgres:15
    container_name: scavenger-hunt-postgres
    environment:
      POSTGRES_USER: scavenger_hunt
      POSTGRES_PASSWORD: scavenger_hunt
      POSTGRES_DB: scavenger_hunt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scavenger_hunt -d scavenger_hunt"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
